### ISSUE TITLE
Trace Replay

### ISSUE THREAD

**Issue by emilemathieu** [yebai/Turing.jl#358] opened 2017-10-18 12:49 UTC
Hi all !

I try to understand these two way to copying particles `TraceR` and `TraceC` and more precisely how they relate to `SMC` and `PG`,  but this is very obscure currently...

Here are my questions:
* are these two different ways to implement particle forking, yet both yielding the same theoretical results (i.e. yield valid samplers) ?
* why `SMC` has `use_replay=false` by default ?
* why in `PG` `fork2(TraceR(model, spl, vi))` is used ? but `resample!(particles, spl.alg.resampler, ref_particle; use_replay=false)` does not use replay ?
* why are there so many `fork`-like functions in `src/trace/trace.jl` ? (`fork`,`forkc`,`forks`,`fork2`)

I'd be very grateful if someone could help me on this !

Best regards,
Emile

**Comment by yebai** [comment] 2017-10-18 17:16
> I try to understand these two way to copying particles `TraceR` and `TraceC` and more precisely how they relate to `SMC` and `PG`,  but this is very obscure currently...

You're right. We probably need some further refactoring in order to make the code more readable, similar to the issue you raised in #359 

> * are these two different ways to implement particle forking, yet both yielding the same theoretical results (i.e. yield valid samplers) ?

Yes - that's right. 

> * why `SMC` has `use_replay=false` by default ?

Unlike CSMC (or PG), SMC does not need a reference particle, so there is no need to store replaying information. In contrast, CSMC uses replaying information to re-create the reference particle.

> why in `PG` `fork2(TraceR(model, spl, vi))` is used ? but `resample!(particles, spl.alg.resampler, ref_particle; use_replay=false)` does not use replay ?

This was meant to improve efficiency - when `use_replay=false`, coroutine copying is used.  It is also correct to use `resample!(particles, spl.alg.resampler, ref_particle; use_replay=true)`, then during the resampling step, all particles (including the reference particle) will be replayed to perform forking. In short:

- `use_replay=false`: use replaying on the reference particle, but use coroutine copying on all other particles
- `use_replay=true`: use replaying for all particles

> why are there so many `fork`-like functions in `src/trace/trace.jl` ? (`fork`,`forkc`,`forks`,`fork2`)

These functions are introduced at different stages, with similar functionality but applicable to different `Trace` types. I agree we should clean up a bit here so the code becomes easier to understand.

**Comment by emilemathieu** [comment] 2017-10-18 23:33
Thanks a lot Hong for these clarifications !
In short, particle copying is faster but the reference particle in CSMC needs replaying information.

Then, why copying is faster ? And why this replaying information is not available when copying the particle ?

**Comment by ae-foster** [comment] 2017-10-19 16:21
Hello all! It looks like in some cases the forking mechanism can lead to segmentation faults:

`signal (11): Segmentation fault
while loading /homes/foster/.julia/v0.5/Turing/my-examples/imm_galaxy.jl, in expression starting on line 43
unknown function (ip: 0x7fca705c2c0f)
jl_gc_collect at /usr/lib64/libjulia.so.0.6 (unknown line)
jl_gc_pool_alloc at /usr/lib64/libjulia.so.0.6 (unknown line)
jl_gc_alloc at /usr/lib64/libjulia.so.0.6 (unknown line)
jl_clone_task at /homes/foster/.julia/v0.5/Turing/deps/libtask.so (unknown line)
copy at /homes/foster/.julia/v0.5/Turing/src/trace/taskcopy.jl:23
forkc at /homes/foster/.julia/v0.5/Turing/src/trace/trace.jl:81
unknown function (ip: 0x7fca75e00622)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:211 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1950
#resample!#33 at /homes/foster/.julia/v0.5/Turing/src/core/container.jl:170
unknown function (ip: 0x7fca75dfd2e0)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:211 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1950
#resample! at ./<missing>:0
unknown function (ip: 0x7fca75dfca1d)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:211 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1950
sample at /homes/foster/.julia/v0.5/Turing/src/samplers/smc.jl:61
unknown function (ip: 0x7fca75deba36)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:211 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1950
do_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:66
eval at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:190
eval_body at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:469
jl_interpret_call at /home/centos/buildbot/slave/package_tarball64/build/src/interpreter.c:573
jl_toplevel_eval_flex at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:572
jl_parse_eval_all at /home/centos/buildbot/slave/package_tarball64/build/src/ast.c:717
jl_load at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:596
jl_load_ at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
unknown function (ip: 0x7fcc9273110b)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:211 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1950
process_options at ./client.jl:265
_start at ./client.jl:321
unknown function (ip: 0x7fcc92756398)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:211 [inlined]
jl_apply_generic at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1950
unknown function (ip: 0x401b3d)
unknown function (ip: 0x401446)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x40148c)
Allocations: 11748728 (Pool: 11747142; Big: 1586); GC: 18
Segmentation fault (core dumped)
`
In this case, I fixed the error by uninstalling and reinstalling Julia and all packages.

I'm brand new to Turing. Are we forking particles by forking OS level processes? This seems very low level (versus iterators, threads, etc). It also brings in these C dependencies which can throw unexpected errors like this! Just wondering what the original rationale for this architecture was :)

**Comment by yebai** [comment] 2017-10-19 16:58
> Hello all! It looks like in some cases the forking mechanism can lead to segmentation faults:

Thanks - it's more likely to be a bug on the Julia side. Nevertheless, it would be easier to help if you have a minimal example that can reproduce the segfault. 

> I'm brand new to Turing. Are we forking particles by forking OS level processes? This seems very low level (versus iterators, threads, etc). It also brings in these C dependencies which can throw unexpected errors like this! Just wondering what the original rationale for this architecture was :)

Turing uses Julia [task](https://docs.julialang.org/en/latest/stdlib/parallel.html#Core.Task) to implement particles, so it is very lightweight and does not involve any OS level operations. Currently, Julia does not natively support coroutine copying (see https://github.com/JuliaLang/julia/issues/12625), so we added a small C file (`deps/task.c`) to implement this feature.

**Comment by xukai92** [comment] 2017-10-19 20:14
@emilemathieu 
> But, why copying is faster ?
Simply because copying means you copy the state of the particle in the memory directly, while replaying means you re-run the program to the state you want to restore.

> Why in forkc do we do newtrace.vi[getretain(newtrace.vi, n_rand, trace.spl)] = NULL ?
Firstly we actually do the same thing in forkr. 

This is an implementation detail to support generic interface - we don't delete things from the VarInfo directly; instead we use NULL, which is a constant (defined in Line 26 in `Turing.jl` file) that says: "this location of VarInfo was used by a particle-based sampler" and when a particle-based sampler is used on this forked particle, please fill up the previous location if the same variable is sampled.

**Comment by ae-foster** [comment] 2017-10-20 12:35
@yebai thanks for the insight. The segfault can be reproduced by simply running
```
Pkg.test("Turing")
```
> Turing uses Julia task to implement particles, so it is very lightweight and does not involve any OS level operations. Currently, Julia does not natively support coroutine copying (see JuliaLang/julia#12625), so we added a small C file (deps/task.c) to implement this feature.

Thanks- very useful. Looks like this feature may well make its way into Julia base soon-ish.

**Comment by ae-foster** [comment] 2017-10-20 12:38
Here's the full output from `Pkg.test("Turing")` leading to a segfault
[error.txt](https://github.com/yebai/Turing.jl/files/1401915/error.txt)

**Comment by emilemathieu** [comment] 2017-11-06 16:14
> This is an implementation detail to support generic interface - we don't delete things from the VarInfo directly; instead we use NULL, which is a constant (defined in Line 26 in Turing.jl file) that says: "this location of VarInfo was used by a particle-based sampler" and when a particle-based sampler is used on this forked particle, please fill up the previous location if the same variable is sampled.

@xukai92 Thanks for your answer, now I understand what `forkc` is doing. Yet I still don't understand why do we need to apply `newtrace.vi[getretain(newtrace.vi, n_rand, trace.spl)] = NULL` ? Since in `step(model::Function, spl::Sampler{PG}, vi::VarInfo)` we already do `vi[getretain(vi, 0, spl)] = NULL`.
Could you please give some explanation/insights on that ?

**Comment by xukai92** [comment] 2017-11-08 14:37
At each step of PG we only need one particle which contains `VarInfo` from the previous step - this is the role of `ref_particle`. Other particles should be new, with variables of other samplers stayed the same.

Thus we have `vi[getretain(vi, 0, spl)] = NULL` as a preparation for the `push!` function to create multiple particles.

**Comment by emilemathieu** [comment] 2017-11-09 22:55
Thanks @xukai92 !
Yet, I believe that doing `newtrace.vi[getretain(newtrace.vi, n_rand, trace.spl)] = NULL` in `forkc(trace :: Trace)` is useless when `trace` is not the reference particle, do you agree ? We only need to remove the remaining randomness for the reference particle.

We may want to do instead
```julia
function forkc(trace :: Trace, is_ref::Bool=false)
...
if is_ref
    n_rand = min(trace.vi.index, length(getvns(trace.vi, trace.spl)))
    newtrace.vi[getretain(newtrace.vi, n_rand, trace.spl)] = NULL
  end
...
end

```

**Comment by emilemathieu** [comment] 2017-11-13 17:17
@yebai what do you think of that ?

**Comment by emilemathieu** [comment] 2017-11-22 13:59
@yebai do you agree with that ?

**Comment by yebai** [comment] 2017-11-22 18:37
> @yebai do you agree with that #358 (comment) ?

Hi Emile, you're right about this - the current code is generic, but actually, the only use case is when copying a reference particle. However, we will need to pass in an additional parameter to tell `forkc` in order to distinguish between normal particles and reference particle. Perhaps we should close this issue and move the discussion to #360.

**Closed** 2017-11-28 23:22 UTC
Labels: discussion, doc, question, refactoring
